### ISSUE TITLE
Can add a video processing feature? 

### ISSUE THREAD

**Issue by kssdxw** [Jeff-LiangF/streamv2v#1]
Can add a video processing feature? My team and I would like to try it out. However, the intranet server does not support the addition of cameras, and due to the lack of certification for pure IP access, we are unable to access the camera on our laptops.

**Comment by Jeff-LiangF** [comment]
Two ways to try our demo when you don't have a local webcam. It might hurt the latency due to the communication overhead:

1). VS Code with [Live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer). When you run the demo on your remote server, the VS Code should direct you to use the local webcam.

2). You can also try with the [huggingface demo](https://huggingface.co/spaces/JeffLiang/streamv2v).

Feel free to re-open the issue if you have further questions.
