### ISSUE TITLE
How do we know which specific celebrities are supported for v2v?

### ISSUE THREAD

**Issue by juc023** [Jeff-LiangF/streamv2v#9]
Hi Jeff,
thank you for your amazing work! I saw that some politicians (e.g., Joe, Donald) are not supported. 
How do we know which specific celebrities are supported for v2v?

**Comment by Jeff-LiangF** [comment]
Hi @juc023 ,

Thanks for your interest in our work. The edit capability is determined by the image editing model: Stable Diffusion + LCM. I am afraid that we can not tell which celebrities are supported by Stable Diffusion + LCM because it is dependent on its training data. 

If you do want to support some specific celebrities or styles, I'd recommend using LoRA for a better editing capability. 

Let me know if you have more questions.
